version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: package
